baseurl = "http://www.phin.tech" # Hostname (and path) to the root.
title = "Sam Phinizy" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Sam Phinizy" # Author's name.
    info = "NGO/non-profit full stack data scientist" # Author's job title or info.
    description = "Sam Phinizy's personal site." # Site description.
    keywords = "blog,developer,personal,datascience,dataviz,visualization" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContent = "" # Add fixedbar content
    fixedbarContentAfter = "" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/nipper"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/phinizy/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/samphinizy/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name = "Portfolio"
    weight = 3
    url = "portfolio"